#!/usr/bin/env python
import sys, os
from subprocess import call

BATCH_FILE = 'temp_batch'

SHARED = '''#!/bin/bash
#SBATCH -p {partition}
#SBATCH -q {qos}
#SBATCH -t {days}-{hours:0>2}:{minutes:0>2}:00   # time in d-hh:mm:ss
#SBATCH -o /scratch/{asurite}/experiments/{name}/%j.out # file to save job's STDOUT (%j = JobId)
#SBATCH -e /scratch/{asurite}/experiments/{name}/%j.err # file to save job's STDERR (%j = JobId)
#SBATCH --mail-user={asurite}@asu.edu # Mail-to address
{mail}
#SBATCH -N 1 
#SBATCH -c {cores}
#SBATCH --job-name={job_name}
'''

GPU = SHARED + '''
#SBATCH --gres=gpu:{gpus} # Request 1 GPU
#SBATCH -C {gputype}
# Cuda library and includes handled naturally:

module load cuda/11.2.0
module load rclone/1.43

export CUDA_VISIBLE_DEVICES=0
export TF_CPP_MIN_LOG_LEVEL=0
export INCLUDEPATH=$INCLUDEPATH:$HOME/cuda/include
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/cuda/lib64
# export XLA_PYTHON_CLIENT_MEM_FRACTION=.7
# Turn off jax debug for now
# export XLA_FLAGS=--xla_dump_to=/scratch/lsaldyt/jax_debug/

echo "Running!\n"
env
module list
nvcc --version
nvidia-smi
./run {name} {args}
'''

CPU = SHARED + '''
#SBATCH --mem={memory}G
module load rclone/1.43
./run {name} {args}'''

# Can be NONE, BEGIN, END, FAIL, REQUEUE, ALL
QUIET = '''#SBATCH --mail-type=FAIL # Send an e-mail only when a job fails '''
LOUD  = '''#SBATCH --mail-type=ALL  # Send an e-mail when a job starts, stops, or fails '''

possible = dict(normal=dict(days=7,
                           hours=0,
                           minutes=0,
                           name='default',
                           qos='normal',
                           nodes=1,
                           cores=8,
                           partition='general',
                           memory=25)
                )

user = os.environ['USER']

def create(name='default', ctype='normal', args=None):
    job_name = name
    quiet = False
    if args is None:
        args = ''
    else:
        if len(args) > 0 and args[-1] == '--quiet':
            quiet = True
            args = args[:-1]
        if len(args) > 1 and args[-2] == '--name':
            job_name = args[-1]
            args = args[:-2]
        args = ' '.join(args)
    final = possible[ctype]
    final['name'] = name
    final['asurite'] = user
    quiet = QUIET if quiet else LOUD
    final.update(dict(mail=quiet, job_name=job_name))
    with open(BATCH_FILE, 'w') as outfile:
        if 'gpu' in ctype:
            outfile.write(GPU.format(args=args, **final))
        else:
            outfile.write(CPU.format(args=args, **final))

ctype = sys.argv[2] if len(sys.argv) >= 3 else 'normal'
create(name=sys.argv[1], ctype=ctype, args=sys.argv[3:])
call(f'mkdir -p /scratch/{user}/experiments/' + sys.argv[1] + '/', shell=True)
call(['sbatch', BATCH_FILE])
